### ISSUE TITLE
タスクバーからタスクトレイに変更してほしい(Support Tasktray)

### ISSUE THREAD

**Issue by yuta0801** [opengl-8080/little-sky#1]
Qiitaの記事を見てとても素晴らしいソフトだったので早速ダウンロードしたのですが、
常時、タスクバーの一角を陣取ってしまうので、標準でタスクトレイに入れるか、
オプションから選択できるようにしてくれると大変助かります。

**Comment by opengl-8080** [comment]
ありがとうございます。

JavaFX でタスクトレイ化はちょっと実装がややこしいっぽいので、とりあえず最初のリリースでは実装しないでおきました。
僕自身、可能ならタスクトレイ化はできたほうがいいかなと思っていたので、おいおい対応してみたいと思います。

**Comment by opengl-8080** [comment]
タスクトレイに対応させました。
以下からダウンロードしてください。

https://github.com/opengl-8080/little-sky/releases/tag/v1.1.0
